# permissions for end users to view memes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meme-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memes/status
  verbs:
  - get
