# permissions for end users to edit memes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meme-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memes/status
  verbs:
  - get
